name: Push Mirror
on:
  workflow_call:
    inputs:
      MIRROR_URL:
        required: true
        type: string
    secrets:
      GIT_SSH_PRIVATE_KEY:
        required: true

jobs:
    push-mirror:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Checkout branch
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Checkout branch
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Mirror
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                  target_repo_url: ${{ inputs.MIRROR_URL }}
                  ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
